### ISSUE TITLE
UI Bugs need to be fixed

### ISSUE THREAD

**Issue by reverope** [ujjawal-1999/DSC-Website#141]
- [x]  Navbar Sign Up and Log in Button Section to the Right. (@KaviiSuri )
- [x]  Dropdown menu for Profile in Navbar.(@KaviiSuri )
- [x]  Mobile Responsive: Get Started Button. (@KaviiSuri )
- [x]  Video Gallery Slider Button on hover state to Cursor. (@reverope )
- [x]  FAQ Section Parellex.(@reverope )
- [x]  Edit Profile Modal Fixing.(@reverope )
- [x] Contact Us Field  Label Animation. (@milibar30 )
- [x]  Upload File button of the FAQ, briefing the file name. (@milibar30 )
- [x] Social Buttons Fix in Register Page (@milibar30 )
- [x] Expanded submit button on click in the forms. (@biley02 )
- [x] Remove Unneccesary padding in the signup form. (@biley02 )
- [x]  FAQ Section Spacing. (@biley02 )
- [x] DSC Founder Members Section UI change. (Arkadeep)
- [x] DSC Hover Card overlap fixing. (Arkadeep)
- [x] Blog Page Cards Fix. (Arkadeep)
- [x] DSC Projects Cards Fix. (Vishal)

**Comment by kashyaparka** [comment]
> * [x]   Navbar Sign Up and Log in Button Section to the Right. (@KaviiSuri )
> * [ x]  Dropdown menu for Profile in Navbar.(@KaviiSuri )
> * [ ]   Mobile Responsive: Get Started Button. (@KaviiSuri )
> * [x]   Video Gallery Slider Button on hover state to Cursor. (@reverope )
> * [x]   FAQ Section Parellex.(@reverope )
> * [x]   Edit Profile Modal Fixing.(@reverope )
> * [ ]  Contact Us Field  Label Animation. (@milibar30 )
> * [ ]   Upload File button of the FAQ, briefing the file name. (@milibar30 )
> * [ ]  Social Buttons Fix in Register Page (@milibar30 )
> * [x]  Expanded submit button on click in the forms. (@biley02 )
> * [x]  Remove Unneccesary padding in the signup form. (@biley02 )
> * [x]   FAQ Section Spacing. (@biley02 )
> * [ ]  DSC Founder Members Section UI change. (Arkadeep)
> * [x]  DSC Hover Card overlap fixing. (Arkadeep)
> * [x]  Blog Page Cards Fix. (Arkadeep)
> * [ ]  DSC Projects Cards Fix. (Vishal)
