### ISSUE TITLE
Testing for Production

### ISSUE THREAD

**Issue by ujjawal-1999** [ujjawal-1999/DSC-Website#163]
- [x] **Login/Signup,Forgot Password (@biley02 )**
- [x]  **Blog Page, create blog and full blog (@KaviiSuri  @arkakashyap)**
- [x] **Profile Page - UI and backend  (@reverope )**
- [x]  **UI testing - Homepage, Members Page (@milibar30 )**
- [x]  **UI testing - Projects Page, Profile Page (@vishalpandeyvip )**

- [x] **Overall Testing - (@knight-18  @ujjawal-1999 )**

**Comment by reverope** [comment]
Profile Page - UI and backend:
1. Experience Description length has to increase a little bit more.
2.  Skills Description length has to increase a little bit more.
3. Personal Projects Hosted URL should not be compulsory for the user.
4.  Achievement Name length has to increase a little bit more.
4.  Achievement Description length has to increase a little bit more.
