### ISSUE TITLE
Google Icon Missing on login/signup page

### ISSUE THREAD

**Issue by knight-18** [ujjawal-1999/DSC-Website#47]
![Screenshot from 2020-09-25 14-50-15](https://user-images.githubusercontent.com/56457032/94250350-c0726880-ff3e-11ea-95b9-adb77854b497.jpg)

Google icon is missing on both login/signup page.

**Comment by reverope** [comment]
There is no issue in the master-clone branch. If the issue reappears, we will fix it.
