### ISSUE TITLE
Add suitable hover effect on file upload button

### ISSUE THREAD

**Issue by knight-18** [ujjawal-1999/DSC-Website#48]
![Screenshot from 2020-09-25 14-53-52](https://user-images.githubusercontent.com/56457032/94250837-5e663300-ff3f-11ea-8d32-51898c842b5c.jpg)

Currently, there is no hover effect for `Upload a File` button in the contact us form. Add a suitable hover effect.

**Comment by milibar30** [comment]
I will make the required changes

**Comment by milibar30** [comment]
The Issue has been resolved and PR has been sent. Please merge

**Comment by ujjawal-1999** [comment]
Kindly, tag the particular issue while making the PR.
