### ISSUE TITLE
Create Public Profile (Replica of Normal Profile Page)

### ISSUE THREAD

**Issue by ujjawal-1999** [ujjawal-1999/DSC-Website#51]
Create a public profile page which will be visible to anyone on the portal. The page shall contain all the details as the normal profile page, except phone no, email, etc (the personal details). Also, that page will only have read only access. 

And link that page to the search bar, so that whenever any users searches the profile of any other user that page is displayed.

Assigned to - @KaviiSuri , biley, arkadeep, @reverope

**Comment by knight-18** [comment]
What is pending here?

**Comment by ujjawal-1999** [comment]
Route left. Will be done by @KaviiSuri today.. 
Closing the issue.
