### ISSUE TITLE
Progress bar on file upload

### ISSUE THREAD

**Issue by ujjawal-1999** [ujjawal-1999/DSC-Website#55]

**Comment by reverope** [comment]
Help, what kind of ?

**Comment by ujjawal-1999** [comment]
I want to show the progress of the file while it is being uploaded to the server. Couldn't figure out a way to grab the browser's progress bar and modify it.

**Comment by reverope** [comment]
There is JS for the same namely index_progressbar. Maybe that helps.

**Comment by ujjawal-1999** [comment]
That doesn't show the progress of the file being uploaded to the server

**Comment by reverope** [comment]
Bhaiya, is this done ??

**Comment by reverope** [comment]
Umm, so client-side uploading will be done in the version.
