### ISSUE TITLE
Project page: Navigation bar and footer to be added

### ISSUE THREAD

**Issue by kashyaparka** [ujjawal-1999/DSC-Website#74]

**Comment by knight-18** [comment]
@kashyaparka what is pending here?

**Comment by kashyaparka** [comment]
Navigation bar and footer to be added in dsc-project page. Till yesterday it was not added ig

**Comment by ujjawal-1999** [comment]
Is it added now?

**Comment by kashyaparka** [comment]
Footer is added. Navbar is left. Will be done before 6pm
