### ISSUE TITLE
Issues to be fixed before deployement

### ISSUE THREAD

**Issue by knight-18** [ujjawal-1999/DSC-Website#81]
- [x] Search bar issue **(Shashwat)** - (Auto hide not implemented yet)

- [x] Form Issue **(Shashwat)**
- [x] Static Project Page **(Arkadeep)**
- [x] Login with Google Icon **(Shashwat)**
- [x] About Us, About Portal Content **(Satyaik)**
- [x] Navbar Tabs **(Shashwat)**
- [x] Remove Features Sections **(Shashwat)**
- [x] Update Schedule thing (Static) **(Satyaik)**
- [x] Fetch YouTube
- [x] Update Footer **(Shashwat)**
- [x] Update Team Pages - **(Vishal)**
- [x] Dark Mode Button Position **(Shashwat)**
- [x] Link all routes
- [x] Profile Image Routes
- [x] Update Profile Image  **(Shashwat)**

- [x] Timeline Backend Issue
- [x] Social Media Links on Profile Page
- [x] Blog Page Author Details **(Biley)**
- [x] Experience Section Change **(Arkadeep)**
- [x] Experience Logo **(Milind)**
- [x] Skills Form Change and render change with icon
- [x]  Projects tab photo **(Milind)**
- [x] Delete routes
- [x]  Add 2 Competition **(Shashwat)**
- [x] Change DSC Logo **(Milind)**
- [x] Create a 404 page
- [x] Unique DSC user handle
- [x] Public Profile Page (To be shown when a user search is done)

**Comment by milibar30** [comment]
I will be working on the small issues regarding the front end.

-experience logo
-projects tab photo
-DSC logo site wide change

**Comment by satyik** [comment]
I will be working on the small issues regarding the front end.

-About Us, About Portal Content
-Blog Page Author Details
-Update Schedule thing (Static)

BTW regarding the Update Schedule thing (Static), could someone please clarify the issue.

**Comment by knight-18** [comment]
@ujjawal-1999 Clarify this update schedule thing.

**Comment by ujjawal-1999** [comment]
There is a section showing schedules in the Home Page. We have to add content to it. Will do that in the end

**Comment by milibar30** [comment]
And what about the project photo thing?

**Comment by ujjawal-1999** [comment]
> I will be working on the small issues regarding the front end.
> 
> -experience logo
> -projects tab photo
> -DSC logo site wide change
> 
> BTW regarding the projects tab photo, could someone please clarify the issue. Its kind of vague. The photo for the tech stack should be received from the database.

We cannot store the images of all the technologies on the database. There are thousands of such technologies. So, will have to keep a default image for that too,

**Comment by milibar30** [comment]
OK understood

**Comment by ujjawal-1999** [comment]
> I will be working on the small issues regarding the front end.
> 
> -About Us, About Portal Content
> -Blog Page Author Details
> -Update Schedule thing (Static)
> 
> BTW regarding the Update Schedule thing (Static), could someone please clarify the issue.

Blog page one has been assigned to Biley as he has been working on it since day one

**Comment by kashyaparka** [comment]
I will be working on

- Project page static
-Experience section Change

(Let me finish this two, then whetever left I will be working on them)

**Comment by kashyaparka** [comment]
> * [x]  Search bar issue **(Shashwat)** - (Auto hide not implemented yet)
> * [x]  Form Issue **(Shashwat)**
> * [x ]  Static Project Page **(Arkadeep)**
> * [x]  Login with Google Icon **(Shashwat)**
> * [ ]  About Us, About Portal Content **(Satyaik)**
> * [x]  Navbar Tabs **(Shashwat)**
> * [x]  Remove Features Sections **(Shashwat)**
> * [ ]  Update Schedule thing (Static) **(Satyaik)**
> * [ ]  Fetch YouTube
> * [x]  Update Footer **(Shashwat)**
> * [x]  Update Team Pages - **(Vishal)**
> * [x]  Dark Mode Button Position **(Shashwat)**
> * [ ]  Link all routes
> * [x]  Profile Image Routes
> * [ ]  Update Profile Image  **(Shashwat)**
> * [ ]  Timeline Backend Issue
> * [ ]  Social Media Links on Profile Page
> * [x]  Blog Page Author Details **(Biley)**
> * [ ]  Experience Section Change **(Arkadeep)**
> * [x]  Experience Logo **(Milind)**
> * [ ]  Skills Form Change and render change with icon
> * [x]   Projects tab photo **(Milind)**
> * [ ]  Delete routes
> * [x]   Add 2 Competition **(Shashwat)**
> * [ ]  Change DSC Logo **(Milind)**
> * [ ]  Create a 404 page
> * [ ]  Unique DSC user handle
> * [ ]  Public Profile Page (To be shown when a user search is done)
